queue: Hosted Linux Preview
# setup build host
steps:
#- checkout: none # skip checkout while debugging
  # install Go
- task: GoTool@0
  displayName: Setup Golang
  inputs:
    version: '1.10'
  # install mage
- script: |
            go get -u -d github.com/magefile/mage
            cd $GOPATH/src/github.com/magefile/mage
            go run bootstrap.go
  displayName: Setup mage make tool
  # install and/or build other dependencies
- script: |
            sudo apt-add-repository ppa:projectatomic/ppa
            sudo apt-get -qq update -y
            sudo apt-get -q install -y skopeo
            sudo apt autoremove
  displayName: Install misc dependencies
  # configure
- script: |
            if [[ -z $OS || -z $VERSION || -z $V8 || -z $NPM || -z $TAG ]]; then
                echo 'one or more variables are undefined, assuming build script debug mode'
                export VERSION=10.0.0
                export OS=centos7
                export V8=6.6.346.24
                export NPM=5.6.0
                export TAG=test-only
                export PREBUILT=true
                export OS=centos7 && source contrib/etc/util.sh
                export FROM_DATA=\"$(getBaseImageForOs)\"
            else
                source contrib/etc/util.sh
                if osSupported ${OS}; then
                    echo ...
                    export FROM_DATA=\"$(getBaseImageForOs)\"
                else
                    echo "Unsupported os: $OS"
                    exit 1
                fi
            fi
            echo "##vso[task.setvariable variable=FROM_DATA]$FROM_DATA"
            echo "##vso[task.setvariable variable=PREBUILT]$PREBUILT"
            echo "##vso[task.setvariable variable=OS]$OS"
            echo "##vso[task.setvariable variable=VERSION]$VERSION"
            echo "##vso[task.setvariable variable=NPM]$NPM"
            echo "##vso[task.setvariable variable=TAG]$TAG"
            echo "##vso[task.setvariable variable=V8]$V8"
  displayName: Configure
  env:
    OS: $(OS)
    VERSION: $(VERSION)
    V8: $(V8)
    NPM: $(NPM)
    TAG: $(TAG)
# info
- script: |
            go get github.com/docker/docker/api/types
            go get github.com/mholt/archiver
            go get github.com/spf13/viper
            export PATH=$PATH:$GOBIN:/usr/share/go/bin
            echo "##vso[task.setvariable variable=PATH]$PATH"
            mage showConfig
  displayName: Info
  env:
    OS: $(OS)
    VERSION: $(VERSION)
    V8: $(V8)
    NPM: $(NPM)
    TAG: $(TAG)
    FROM_DATA: $(FROM_DATA)
    PREBUILT: $(PREBUILT)
#- script: |
#            export PATH=$PATH:$GOBIN:/usr/share/go/bin
#            go get github.com/docker/docker/api/types
#            go get github.com/mholt/archiver
#            go get github.com/spf13/viper
#            mage showConfig
#  displayName: Info
- script: |
            mage installSources
  displayName: Install Sources
  env:
    PATH: $(PATH)
- script: |
            mage build
  displayName: Build
  env:
    PATH: $(PATH)
- script: |
            if [ "$OS" == "rhel7" ]; then
                mage archive
            else
                echo "OS is not [rhel7] not archiving"
            fi
  displayName: Archive
  env:
    OS: $(OS)
    PATH: $(PATH)
- script: |
            if [ "$OS" == "rhel7" ]; then
                echo "access_key = $AWS_ACCESS_KEY_ID" >> ~/.s3cfg
                echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> ~/.s3cfg
                mage upload
            else
                echo "OS is not [rhel7] not uploading"
            fi
  displayName: Upload
  env:
    OS: $(OS)
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    PATH: $(PATH)
- script: |
            mage squash
  displayName: Docker squash
  env:
    PATH: $(PATH)
- script: |
            mage test
  displayName: Test
  env:
    PATH: $(PATH)
- script: |
            if [ "$OS" == "rhel7" ]; then
                echo "OS is [rhel7] not publishing to Docker Hub"
            else
                mage publish
            fi
  displayName: Publish to Docker Hub
  env:
    PATH: $(PATH)
    OS: $(OS)
- script: |
            if [ "$OS" == "rhel7" ]; then
                source contrib/etc/util.sh
                if ! isDebug && shouldPublish; then
                    export RH_SECRET=$(getProjectSecret)
                    export RH_ENDPOINT="scan.connect.redhat.com"
                    export RH_PROJECT=$(getProjectId)
                    mage publishRedHat
                fi
            else
                echo "OS is not [rhel7] not publishing to Red Hat Catalog"
            fi
  displayName: Publish to Red Hat
  env:
    OS: $(OS)
    PATH: $(PATH)
