#!/bin/sh

if [ -f /etc/os-release ]; then
    . /etc/os-release
    ID=$ID
    VER=$VERSION_ID
else
    ID=centos
    VER=7
fi
OS=${ID}${VER}

cat <<EOF
This is a Source2Image base for Nodejs:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:
s2i build https://github.com/nearform/nodejs-distribution --context-dir=contrib/demo nearform/${OS}-s2i-nodejs:8 demo-app-${OS}

You can then run the resulting image via:
docker run -p 8080:8080 demo-app-${OS}
EOF
